### ISSUE TITLE
Add option to change main background color

### ISSUE THREAD

**Issue by Keith94** [JakobJFL/Hue-Browser-Controller#11]
In the app version, it'd be nice to change the background from purple to something else, even by e.g. adding a hex code to a config file

**Comment by Keith94** [comment]
In the web version, it can be forced by injecting some simple css
```css
body { 
  background: #000c;
}
```
