### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by benniblot** [JakobJFL/Hue-Browser-Controller#14]
Hey, had the idea for a apache docker image with hue-browser-controller inside it that exposed a port so you can access it.

**Comment by rpsteinbrueck** [comment]
Hi,

I don't have an apache docker image for you but I have a nginx docker image instead.

If you just quickly want to simple setup you can execute the following line in the terminal (Note, change folder path.):
`docker run -it --rm -d -p 8881:80 --name Hue-Browser-Controller -v /PATH/TO/FOLDER/Hue-Browser-Controller:/usr/share/nginx/html nginx`


I also have a Dockerfile and a docker-compose.yaml
Place both files in a folder and just run `docker-compose up -d` when you are in the folder.
The nginx docker image is alpine and installs git and then downloads this repository to the default nginx folder /usr/share/nginx/html.

Dockerfile:
```
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html

RUN apk add git
RUN git clone https://github.com/JakobJFL/Hue-Browser-Controller /usr/share/nginx/html

EXPOSE 80
```

docker-compose.yaml:
```
# compose file for hue-browser-controller
version: '3'

networks:
  hue-browser-controllernetwork_compose:
    driver: bridge

services:
  hue-browser-controller:
    build: .
    restart: unless-stopped
    networks:
      hue-browser-controllernetwork_compose:
    ports:
    - "8881:80"
```

I hope this helps.

EDIT: You can reach the container over localhost:8881 or HOST_IP:8881
